### ISSUE TITLE
Elm registry points to non-existent 2.0.8

### ISSUE THREAD

**Issue by 1602** [Skinney/murmur3#10]
Latest version of this package according to elm registry is 2.0.8 https://package.elm-lang.org/packages/Skinney/murmur3/latest/
This results in 404 when trying to install some indirect dependencies. Any chance of making 2.0.8 tag?

**Comment by 1602** [comment]
This still seems to be an issue in the registry.

**Comment by robinheghan** [comment]
It is. But I cannot change the registry 🤷‍♂️

**Comment by 1602** [comment]
I believe pushing the 2.0.8 tag to this repository would resolve the issue.

**Comment by robinheghan** [comment]
It wouldn't. The hashes for the release of `robinheghan/murmur3: 2.0.8` and `Skinney/murmur3: 2.0.8` would be different.
