### ISSUE TITLE
archive hash changed ?

### ISSUE THREAD

**Issue by clairepoyols** [Skinney/murmur3#5]
Hello there, 

This morning, i am encountering a problem with murmur3 dependency. Here is the warning that i've got in my terminal.

```
Downloaded the source code for Skinney/murmur3 2.0.8 from: https://github.com/Skinney/murmur3/zipball/2.0.8/        

But it looks like the hash of the archive has changed since publication:        
Expected: 81a0bada79740ae806df04b1bb14a7d64f763ac5        
Actual: 931398ec656078e26b2e29520cd283ffe6e8e441     
   
This usually means that the package author moved the version tag, so report it  to them and see if that is the issue. Folks on Elm slack can probably help as well.      
```  

Could something be done ?

**Comment by mattjbray** [comment]
Looks like this is because of the repo transfer from `Skinney` to `robinheghan`.

GitHub redirects `https://github.com/Skinney/murmur3/zipball/2.0.8/` to `https://github.com/robinheghan/murmur3/zipball/2.0.8`, but the new zip archive has the new repo name:

```
$ unzip -l murmur3.zip                                                                                                                                                                                                               
Archive:  murmur3.zip
6a72dbab1551a2019ef52f793f5dc689a971d535
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  09-18-2018 21:49   robinheghan-murmur3-6a72dba/
       62  09-18-2018 21:49   robinheghan-murmur3-6a72dba/.gitignore
      603  09-18-2018 21:49   robinheghan-murmur3-6a72dba/Changelog.md
     1087  09-18-2018 21:49   robinheghan-murmur3-6a72dba/LICENSE
      355  09-18-2018 21:49   robinheghan-murmur3-6a72dba/README.md
        0  09-18-2018 21:49   robinheghan-murmur3-6a72dba/bench/
      583  09-18-2018 21:49   robinheghan-murmur3-6a72dba/bench/Main.elm
      753  09-18-2018 21:49   robinheghan-murmur3-6a72dba/bench/elm.json
       68  09-18-2018 21:49   robinheghan-murmur3-6a72dba/bench/prep-bench.sh
      426  09-18-2018 21:49   robinheghan-murmur3-6a72dba/elm.json
    99504  09-18-2018 21:49   robinheghan-murmur3-6a72dba/package-lock.json
      437  09-18-2018 21:49   robinheghan-murmur3-6a72dba/package.json
        0  09-18-2018 21:49   robinheghan-murmur3-6a72dba/src/
     2605  09-18-2018 21:49   robinheghan-murmur3-6a72dba/src/Murmur3.elm
        0  09-18-2018 21:49   robinheghan-murmur3-6a72dba/tests/
      613  09-18-2018 21:49   robinheghan-murmur3-6a72dba/tests/Tests.elm
---------                     -------
   107096                     16 files

```

**Comment by francescortiz** [comment]
Can you create a project with the old name and leave the file there?

**Comment by francescortiz** [comment]
Another option is to create a release with irrelevant change, like a new exposed variable with the version, so that you can make a new minor release.

**Comment by ocharles** [comment]
Doesn't it just need @robinheghan to release the package into their namespace on `packages.elm-lang.org`? It will mean anything downstream will have to update their dependencies though.

**Comment by neslinesli93** [comment]
FYI if you are using [dillonkearns/elm-graphql](https://github.com/dillonkearns/elm-graphql), the latest version has fixed the Murmur dependency issue :)

**Comment by lukaszklis** [comment]
I’ve just found a temporary fork of the repo which was published to the registry: https://package.elm-lang.org/packages/proda-ai/murmur3/1.0.0/

**Comment by tanakadesilva** [comment]
We published a copy of this package (`murmur3`) and `elm-css` using the forked version of `murmur3` as we needed to get our CI servers working again until a permanent solution is found.

**Comment by davidjb99** [comment]
elm-css is now fixed to reflect this, upgrade to 16.1

https://github.com/rtfeldman/elm-css/commit/c01101a8e4f3b36a1577690885b706734f619db1

**Comment by 0-gravity** [comment]
> elm-css is now fixed to reflect this, upgrade to 16.1
> 
> [rtfeldman/elm-css@c01101a](https://github.com/rtfeldman/elm-css/commit/c01101a8e4f3b36a1577690885b706734f619db1)

I confirm. Installed latest version of elm-css and removed indirect dependency for mummur from elm.json

**Comment by robinheghan** [comment]
I've now republished this package under my new username. It will require all downstream dependencies to update their dependencies, which sucks, but hopefully this will just be a temporary setback.

**Comment by maxfarseer** [comment]
@robinheghan what can we do, if we can't update elm-css to new version? (we have projects with elm 0.18)

**Comment by robinheghan** [comment]
Fork `elm-css` and publish your own version of it with the new dependency.
