### ISSUE TITLE
Install on 0.18 does not work

### ISSUE THREAD

**Issue by debjitbis08** [Skinney/murmur3#6]
We have been using package with Elm 0.18, but after the transfer, those old version references are no longer valid. Is there any plan to support Elm 0.18. Also, is there any short term fix?

**Comment by ream88** [comment]
Yeah please fix this, it broke our CI as well 😞

**Comment by ream88** [comment]
Hey I just saw you fixed https://github.com/Skinney/elm-array-exploration! Can you please do the same for this repo?

**Comment by ream88** [comment]
~~@debjitbis08 I fixed it by updating `elm-css` to `16.1.0`.~~

**EDIT**: Nope, still not working. I copied both `elm-css` and `murmur3` into my codebase.

**Comment by robinheghan** [comment]
0.19 was released nearly two years ago. There are no plans to support any older version.

I did not fix `elm-array-exploration`, someone else registered the `Skinney` username after I changed mine. Don't know who released that package 🤷‍♂️
