### ISSUE TITLE
Re-release broke installation?

### ISSUE THREAD

**Issue by ghost** [Skinney/murmur3#7]
I cleared my local elm-cache to reproduce this error from CI. It seems your release has broken installation through the Elm CLI.

I get:
```

Verifying dependencies (21/21)-- PROBLEM DOWNLOADING PACKAGE -------------------------------------------------
--
Dependency problem!
-- PROBLEM DOWNLOADING PACKAGE -------------------------------------------------

I was trying to download the source code for Skinney/murmur3 2.0.8, so I tried
to fetch:

    https://github.com/Skinney/murmur3/zipball/2.0.8/

But it came back as 404 Not Found

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!
```

**Comment by wadouk** [comment]
For me this dependency is needed by [elm-css](https://package.elm-lang.org/packages/rtfeldman/elm-css/latest/)

The last version doesn't need this dependency anymore
Don't find with regular elm package manager how to upgrade a dependcy so i use [elm-json](https://github.com/zwilias/elm-json#example-installing-the-latest-available-2xx-version-of-a-package) to do it
`elm-json install rtfeldman/elm-css@16.1.0`

And all goes OK

**Comment by HenkPoley** [comment]
How do you prune 2.0.8 (pre-re-release) from your local cache? elm or elm-json keeps wanting to install 2.0.8 as a direct dependency.

This is not enough:
```
rm ~/.elm/0.19.1/packages/registry.dat
rm -rf ~/.elm/0.19.1/packages/Skinney/murmur3
rm -rf ~/.elm/elm-json/packages/Skinney/murmur3
```

Even `rm -rf ~/.elm` ..

Normally you'd go to a 3.x version isn't it? And keep the 2.0.8 downloads.

Edit: Ah I see, it's now *robinheghan*/murmur3, instead of *Skinney*/murmur3. E.g.

```
elm-json uninstall Skinney/murmur3
elm-json install robinheghan/murmur3@1.0.0
```

**Comment by wadouk** [comment]
You have to check with elm-json why you need Skinney/murmur3@2.0.8
For me it was for elm-css.
You have to remove why you need this module/version. Removing it from local cache is not sufficient.
