### ISSUE TITLE
Version 2.0.8 removed?  Causes build failures for existing projects.

### ISSUE THREAD

**Issue by jmbromley** [Skinney/murmur3#9]
Hi,

I have an existing Elm 0.19 project using murmur3.  But lately when I try to build it on a fresh system where murmur3 is not already cached in ~/.elm I am seeing build errors of the form:

```
-- PROBLEM DOWNLOADING PACKAGE -------------------------------------------------

I was trying to download the source code for Skinney/murmur3 2.0.8, so I tried
to fetch:

    https://github.com/Skinney/murmur3/zipball/2.0.8/

But it came back as 404 Not Found
```

Was there a version downgrade?  Was something wrong with the previous version?  Presumably the solution is to manually remove murmur3 from my elm.json and then try to reinstall?

Thanks!

**Comment by robinheghan** [comment]
Previous discussion: https://github.com/robinheghan/murmur3/issues/8
